// Closed, vendor-neutral, versioned vocabulary of generic API and resource
// words (L0 r3, positive structural proof (a)). A path word is transmitted in
// the structure digest ONLY if it is listed here (or is a version marker such
// as `v2`). Every other word is a device-held session slot. Additions are a
// contract change: bump VOCABULARY_VERSION and mirror the change in the
// backend copy so cross-repo fingerprints keep matching.
export const VOCABULARY_VERSION = 1;

export const VERSION_MARKER = /^v\d{1,3}$/i;

const WORDS = [
  // transport / infrastructure
  "api",
  "rest",
  "graphql",
  "proxy",
  "internal",
  "public",
  "web",
  "app",
  "mobile",
  "admin",
  "auth",
  "me",
  "current",
  "self",
  "search",
  "list",
  "all",
  "items",
  "data",
  "index",
  "export",
  "import",
  "batch",
  "bulk",
  "settings",
  "preferences",
  "account",
  "accounts",
  "session",
  "sessions",
  "status",
  "health",
  // people
  "user",
  "users",
  "profile",
  "profiles",
  "coach",
  "coaches",
  "trainer",
  "trainers",
  "client",
  "clients",
  "member",
  "members",
  "athlete",
  "athletes",
  "customer",
  "customers",
  "contact",
  "contacts",
  "team",
  "teams",
  "group",
  "groups",
  "roster",
  "staff",
  // training
  "workout",
  "workouts",
  "program",
  "programs",
  "plan",
  "plans",
  "exercise",
  "exercises",
  "movement",
  "movements",
  "routine",
  "routines",
  "template",
  "templates",
  "library",
  "libraries",
  "block",
  "blocks",
  "cycle",
  "cycles",
  "phase",
  "phases",
  "week",
  "weeks",
  "day",
  "days",
  "set",
  "sets",
  "reps",
  "weight",
  "weights",
  "log",
  "logs",
  "history",
  "activity",
  "activities",
  "event",
  "events",
  "calendar",
  "schedule",
  "schedules",
  "appointment",
  "appointments",
  "booking",
  "bookings",
  "video",
  "videos",
  // communication
  "message",
  "messages",
  "conversation",
  "conversations",
  "thread",
  "threads",
  "chat",
  "chats",
  "comment",
  "comments",
  "note",
  "notes",
  "notification",
  "notifications",
  "feed",
  "timeline",
  "announcement",
  "announcements",
  // tracking
  "habit",
  "habits",
  "task",
  "tasks",
  "goal",
  "goals",
  "metric",
  "metrics",
  "measurement",
  "measurements",
  "progress",
  "photo",
  "photos",
  "media",
  "file",
  "files",
  "attachment",
  "attachments",
  "document",
  "documents",
  "check-in",
  "check-ins",
  "checkin",
  "checkins",
  "assessment",
  "assessments",
  "form",
  "forms",
  "questionnaire",
  "questionnaires",
  "survey",
  "surveys",
  "intake",
  "stats",
  "summary",
  "summaries",
  "dashboard",
  "report",
  "reports",
  // nutrition
  "nutrition",
  "meal",
  "meals",
  "food",
  "foods",
  "recipe",
  "recipes",
  "macro",
  "macros",
  "diet",
  "diets",
  "supplement",
  "supplements",
  // commerce
  "payment",
  "payments",
  "invoice",
  "invoices",
  "subscription",
  "subscriptions",
  "product",
  "products",
  "package",
  "packages",
  "plan-tier",
  "pricing",
  "orders",
  "order",
  // taxonomy / state
  "tag",
  "tags",
  "category",
  "categories",
  "type",
  "types",
  "archive",
  "archived",
  "active",
  "inactive",
  "pending",
  "completed",
  "draft",
  "drafts",
  "detail",
  "details",
  "page",
  "pages",
  "count",
  "total",
  "new",
  "edit",
  "show",
  "view",
  "recent",
  "upcoming",
  "past",
];

export const VOCABULARY = Object.freeze(new Set(WORDS));

// True when a decoded, non-empty path word may appear in clear.
export function isStructuralWord(word) {
  if (typeof word !== "string") return false;
  const lower = word.toLowerCase();
  return VERSION_MARKER.test(lower) || VOCABULARY.has(lower);
}
